apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: template-ui
  labels:
    app: template-ui
    component: ui
spec:
  successfulBuildsHistoryLimit: 1
  failedBuildsHistoryLimit: 1
  output:
    to:
      kind: ImageStreamTag
      name: template-ui:latest
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
      volumes:
        - name: npm-cache
          mounts:
            - destinationPath: /opt/app-root/src/.npm
          source:
            type: PersistentVolumeClaim
            claimName: template-ui-build-cache
  resources:
    requests:
      memory: "4Gi"
      cpu: "2000m"
    limits:
      memory: "8Gi"
      cpu: "8"
  triggers: []

