apiVersion: v1
kind: ConfigMap
metadata:
  name: template-ui-config
  labels:
    app: template-ui
    component: ui
data:
  ENVIRONMENT: "production"
  AUTH_ENABLED: "true"
  SSO_ISSUER_HOST: "https://auth.redhat.com/auth/realms/EmployeeIDP"
  SSO_CALLBACK_URL: "https://template-ui.apps.example.openshift.com/auth/callback/oidc"
  AGENT_HOST: "https://template-agent.apps.example.openshift.com"

