apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - buildconfig.yaml
  - imagestream.yaml
  - configmap.yaml
  # - secret.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
labels:
  - pairs:
      app: template-ui
      component: ui
    includeSelectors: true

